### PR TITLE
Switch to Go modules

### PR DESCRIPTION
**Pull request by lawrencejones**
Stolon uses Go modules and it makes it slightly easier to compare
dependencies if we're on the same system. This also seems to be gaining
the mind-share.

### CODE REVIEW

**Comment by hmac** [comment]
I guess we're not so worried about our dependencies disappearing, then? Are we able to use modules _with_ vendoring?

**Comment by lawrencejones** [comment]
Yeah sorry, this is with vendoring. The go module flow is `go get && go mod vendor`

**Comment by lawrencejones** [comment]
I think the diff here is misleading- it's just cleaned up some unnecessary vendored packages rather than removed them all. Vendor is still a fat 21MB:

```
$ du -sh vendor
 21M    vendor
```

**Comment by hmac** [comment]
Ah sweet.

**Pull request merged**
